/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_ayala_version_console;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author ayala
 */
public class FenetrePrincipale extends javax.swing.JFrame {
        GrilleDeJeu grille;
        int nbCoups;
        int i;
        int j;
        int nbCoupsMax;
        int diff =0;
        
    
        
    public void initialiserPartie() {
    grille.eteindreToutesLesCellules();
    grille.melangerMatriceAleatoirement(10000);
}
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale(int nbLignes, int nbColonnes, int nbCoupsMax, int diff) {
        initComponents();
        this.nbCoups = 0;
        this.nbCoupsMax = nbCoupsMax;
        this.grille = new GrilleDeJeu(nbLignes, nbColonnes, diff);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        initialiserPartie();
        for (int i=0; i < nbLignes; i++) {
        for (int j=0; j < nbColonnes; j++ ) {
        CelluleGraphique bouton_cellule = new CelluleGraphique( grille.matriceCellules[i][j], 500/nbColonnes,450/nbLignes);
        PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
        jLabel1.setText("Nombre de coups restants :" + (nbCoupsMax -nbCoups));
}
}
        PanneauBoutonVerticaux.setLayout(new GridLayout(nbLignes, 1));
        PanneauBoutonHorizontaux.setLayout(new GridLayout(1, nbColonnes));
        //getContentPane().add(PanneauBoutonVerticaux, new
        //org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1 * 40, nbLignes * 40));
       // this.pack();
       // this.revalidate();
            
        
        // création du panneau de boutons verticaux (pour les lignes)
    for (i = 0; i < nbLignes; i++) {
    JButton bouton_ligne = new JButton();
    ActionListener ecouteurClick = new ActionListener() {
    final int j = i;
    @Override
    public void actionPerformed(ActionEvent e) {
    grille.activerLigneDeCellules(j);
    nbCoups ++;
    jLabel1.setText("Nombre de coups restants :" + (nbCoupsMax -nbCoups));
    if (nbCoups == nbCoupsMax){
        FenetreDefaite f = new FenetreDefaite() ;
        f.setVisible(true) ;
    }
    if (grille.cellulesToutesEteintes() == true){
        FenetreVictoire f = new FenetreVictoire();
        f.setVisible(true) ;
       
    }
     
    repaint();
}
};
bouton_ligne.addActionListener(ecouteurClick);
PanneauBoutonVerticaux.add(bouton_ligne);
}
    for (j = 0; j < nbColonnes; j++) {
    JButton bouton_colonne = new JButton();
    ActionListener ecouteurClick = new ActionListener() {
    final int i = j;
    @Override
    public void actionPerformed(ActionEvent e) {
    grille.activerColonneDeCellules(i);
    nbCoups ++;
    jLabel1.setText("Nombre de coups restants :" + (nbCoupsMax -nbCoups));
    if (nbCoups == nbCoupsMax){
        FenetreDefaite f = new FenetreDefaite() ;
        f.setVisible(true) ;
    }
    if (grille.cellulesToutesEteintes() == true){
        FenetreVictoire f = new FenetreVictoire();
        f.setVisible(true) ;
        
    }
    repaint();
}
};
bouton_colonne.addActionListener(ecouteurClick);
PanneauBoutonHorizontaux.add(bouton_colonne);



}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        PanneauBoutonVerticaux = new javax.swing.JPanel();
        PanneauBoutonHorizontaux = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 500, 450));

        PanneauBoutonVerticaux.setBackground(new java.awt.Color(0, 0, 204));
        PanneauBoutonVerticaux.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout PanneauBoutonVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonVerticaux);
        PanneauBoutonVerticaux.setLayout(PanneauBoutonVerticauxLayout);
        PanneauBoutonVerticauxLayout.setHorizontalGroup(
            PanneauBoutonVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        PanneauBoutonVerticauxLayout.setVerticalGroup(
            PanneauBoutonVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 70, 50, 450));

        PanneauBoutonHorizontaux.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout PanneauBoutonHorizontauxLayout = new javax.swing.GroupLayout(PanneauBoutonHorizontaux);
        PanneauBoutonHorizontaux.setLayout(PanneauBoutonHorizontauxLayout);
        PanneauBoutonHorizontauxLayout.setHorizontalGroup(
            PanneauBoutonHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanneauBoutonHorizontauxLayout.setVerticalGroup(
            PanneauBoutonHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 500, 40));

        jButton1.setText(".");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jButton2.setText(".");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        jLabel1.setText("Nombre de coups restants");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.grille.activerDiagonaleDescendante();
        nbCoups ++;
        jLabel1.setText("Nombre de coups restants :" + (nbCoupsMax -nbCoups));
        if (nbCoups == nbCoupsMax){
        FenetreDefaite f = new FenetreDefaite() ;
        f.setVisible(true) ;
        this.dispose();
    }
        if (grille.cellulesToutesEteintes() == true){
        FenetreVictoire f = new FenetreVictoire();
        f.setVisible(true) ;
        this.dispose();
    }
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.grille.activerDiagonaleMontante();
        nbCoups ++;
        jLabel1.setText("Nombre de coups restants :" + (nbCoupsMax -nbCoups));
        if (nbCoups == nbCoupsMax){
        FenetreDefaite f = new FenetreDefaite() ;
        f.setVisible(true) ;
        this.dispose();
    }
        if (grille.cellulesToutesEteintes() == true){
        FenetreVictoire f = new FenetreVictoire();
        f.setVisible(true) ;
        this.dispose();
    }
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }    
/*
    
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonHorizontaux;
    private javax.swing.JPanel PanneauBoutonVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
